### ISSUE TITLE
Feature Request: Double click to automatically add card to pool instead of dragging

### ISSUE THREAD

**Issue by AbstractAlgebra** [jjallaire/draftpod#61]
For someone who likes to draft a lot, this is less movement than having to drag the card. It could automatically go to a column by CMC, or just the first column.

**Comment by jjallaire** [comment]
Thanks for the feedback! Just implemented here: https://github.com/jjallaire/draftpod/commit/7a13c34fddeb0e08097a253c9728d24a914a9642
