### ISSUE TITLE
Bug: Deck export limits sideboard to 15 cards

### ISSUE THREAD

**Issue by JohnReagan** [jjallaire/draftpod#76]
Hey, I've been using this app for a while and really enjoy it to play with friends!

Found a bug today playing a 2 player Kaldheim sealed game. When exporting decklist, the sideboard only includes first 15 cards in "View Decklist" text field. Would be a great fix as swapping decks is common use cases. 

Link to pool: https://draftpod.org/sealed/tjeq43H4j8CcmnYjMs8XFV

**Comment by jjallaire** [comment]
Thanks for the report! Should be fixed here: https://github.com/jjallaire/draftpod/commit/ec9cdf0dd989a8fbf081d6fe144f69405e5cd526
