### ISSUE TITLE
Drag & Drop fails when Dropping on Previews

### ISSUE THREAD

**Issue by tdnzr** [jjallaire/draftpod#84]
I like the draft previews on draftpod.org, and prefer them to the way e.g. draftsim depicts stuff.

The problem: In contrast to e.g. MTGA, I cannot drag & drop my cards around as I want, because the card previews get in the way. One basically can't drag a card and drop it one column to the right, because that would drop it onto its card preview.

Here's a [gif](https://i.imgur.com/mdg7TTs.gif) to illustrate this problem.

Desired behavior: Ability to drag & drop even on top of card previews.

EDIT: In case this problem is browser-dependent, this happened on desktop Firefox, v96.0.3.

**Comment by jjallaire** [comment]
Thanks for reporting this! Should be fixed here: https://github.com/jjallaire/draftpod/commit/af8d23a41af0b6657c7236a3be3e37c3ae8761b1

I hadn't seen this before b/c it doesn't occur in Chrome, however I was able to repro (and verify the fix) in Firefox
